import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt

gdf_neighbourhoods = gpd.read_file("/workspaces/Buying-vs.-Renting-a-Property-in-Toronto/data/frontend/toronto158neighbourhoods.geojson")

trreb_mapping = {
    "South Eglinton-Davisville": "C10",
    "North Toronto": "C10",
    "Dovercourt Village": "W02",
    "Junction-Wallace Emerson": "W02",
    "Yonge-Bay Corridor": "C01",
    "Bay-Cloverhill": "C01",
    "Bendale-Glen Andrew": "E09",
    "Downsview": "W05",
    "Oakdale-Beverley Heights": "W05",
    "Avondale": "C14",
    "East Willowdale": "C14",
    "Yonge-Doris": "C14",
    "Fenside-Parkwoods": "C13",
    "Parkwoods-O'Connor Hills": "C13",
    "East L'Amoreaux": "E05",
    "L'Amoreaux West": "E05",
    "Malvern East": "E11",
    "Malvern West": "E11",
    "Morningside Heights": "E11",
    "West Rouge": "E10",
    "Woburn North": "E09",
    "Golfdale-Cedarbrae-Woburn": "E09",
    "Guildwood": "E08",
    "Scarborough Village": "E08",
    "Eglinton East": "E08",
    "West Hill": "E10",
    "Morningside": "E09",
    "Highland Creek": "E10",
    "Centennial Scarborough": "E10",
    "Milliken": "E07",
    "Agincourt North": "E07",
    "Agincourt South-Malvern West": "E07",
    "Dorset Park": "E04",
    "Ionview": "E04",
    "Kennedy Park": "E04",
    "Cliffcrest": "E08",
    "Birchcliffe-Cliffside": "E06",
    "Downtown Yonge East": "C08",
    "Church-Wellesley": "C08",
    "St Lawrence-East Bayfront-The Islands": "C08",
    "Harbourfront-CityPlace": "C01",
    "Wellington Place": "C01",
    "Fort York-Liberty Village": "C01",
    "West Queen West": "C01",
    "Humber Bay Shores": "W06",
    "Mimico-Queensway": "W06",
    "Etobicoke City Centre": "W08",
    "Islington": "W08",
    "Bendale South": "E09",
    "Caledonia-Fairbank": "W03",
    "Briar Hill-Belgravia": "W04",
    "Oakwood Village": "C03",
    "Humewood-Cedarvale": "C03",
    "Lawrence Park North": "C04",
    "Lawrence Park South": "C04",
    "Forest Hill North": "C04",
    "Forest Hill South": "C03",
    "Yonge-Eglinton": "C03",
    "Mount Pleasant East": "C10",
    "Rosedale-Moore Park": "C09",
    "Yonge-St.Clair": "C02",
    "Casa Loma": "C02",
    "Annex": "C02",
    "Wychwood": "C02",
    "Corso Italia-Davenport": "W03",
    "Weston-Pelham Park": "W03",
    "Junction Area": "W02",
    "Oakridge": "E06",
    "Clairlea-Birchmount": "E04",
    "Wexford/Maryvale": "E04",
    "Tam O'Shanter-Sullivan": "E05",
    "Steeles": "E05",
    "Mount Dennis": "W04",
    "Lambton Baby Point": "W02",
    "Weston": "W04",
    "Beechborough-Greenbrook": "W04",
    "Rockcliffe-Smythe": "W03",
    "Keelesdale-Eglinton West": "W03",
    "Palmerston-Little Italy": "C01",
    "University": "C01",
    "Kensington-Chinatown": "C01",
    "North St.James Town": "C08",
    "Moss Park": "C08",
    "Regent Park": "C08",
    "Cabbagetown-South St.James Town": "C08",
    "South Riverdale": "E01",
    "Blake-Jones": "E01",
    "North Riverdale": "E01",
    "Playter Estates-Danforth": "E03",
    "Danforth": "E03",
    "Greenwood-Coxwell": "E01",
    "Woodbine Corridor": "E02",
    "The Beaches": "E02",
    "East End-Danforth": "E02",
    "Taylor-Massey": "E03",
    "Woodbine-Lumsden": "E03",
    "Danforth East York": "E03",
    "Old East York": "E03",
    "Runnymede-Bloor West Village": "W02",
    "High Park North": "W02",
    "High Park-Swansea": "W01",
    "Roncesvalles": "W01",
    "South Parkdale": "W01",
    "Little Portugal": "C01",
    "Dufferin Grove": "C01",
    "Trinity-Bellwoods": "C01",
    "Don Valley Village": "C15",
    "Pleasant View": "C15",
    "Flemingdon Park": "C11",
    "Victoria Village": "C13",
    "Banbury-Don Mills": "C13",
    "Bridle Path-Sunnybrook-York Mills": "C12",
    "St.Andrew-Windfields": "C12",
    "Bedford Park-Nortown": "C04",
    "Lansing-Westgate": "C07",
    "Willowdale West": "C07",
    "Newtonbrook West": "C07",
    "Westminster-Branson": "C07",
    "Bathurst Manor": "C06",
    "Clanton Park": "C06",
    "Englemount-Lawrence": "C04",
    "Yorkdale-Glen Park": "W04",
    "Brookhaven-Amesbury": "W04",
    "Maple Leaf": "W04",
    "Rustic": "W04",
    "York University Heights": "W05",
    "Glenfield-Jane Heights": "W05",
    "Broadview North": "E03",
    "Leaside-Bennington": "C11",
    "Thorncliffe Park": "C11",
    "O'Connor-Parkview": "E03",
    "Henry Farm": "C15",
    "Bayview Village": "C15",
    "Newtonbrook East": "C14",
    "Bayview Woods-Steeles": "C15",
    "Hillcrest Village": "C15",
    "Alderwood": "W06",
    "Long Branch": "W06",
    "New Toronto": "W06",
    "Stonegate-Queensway": "W07",
    "Kingsway South": "W08",
    "Etobicoke West Mall": "W08",
    "Markland Wood": "W08",
    "Eringate-Centennial-West Deane": "W08",
    "Princess-Rosethorn": "W08",
    "Edenbridge-Humber Valley": "W08",
    "Humber Heights-Westmount": "W09",
    "Willowridge-Martingrove-Richview": "W09",
    "Kingsview Village-The Westway": "W09",
    "Elms-Old Rexdale": "W10",
    "Rexdale-Kipling": "W10",
    "Thistletown-Beaumond Heights": "W10",
    "Mount Olive-Silverstone-Jamestown": "W10",
    "West Humber-Clairville": "W10",
    "Black Creek": "W05",
    "Pelmo Park-Humberlea": "W04",
    "Humbermede": "W05",
    "Humber Summit": "W05"
}

gdf_neighbourhoods['TRREB_Zone'] = gdf_neighbourhoods['AREA_NAME'].map(trreb_mapping)
gdf_neighbourhoods.to_file("/workspaces/Buying-vs.-Renting-a-Property-in-Toronto/data/gdf_neighbourhoods.geojson", driver="GeoJSON")

# This tells Geopandas: "Find every row with 'W01', delete the internal borders between them, and melt them into one giant polygon."
trreb_map = gdf_neighbourhoods.dissolve(by='TRREB_Zone')

# 5. Optional: Reset the index so TRREB_Zone becomes a normal column again
trreb_map = trreb_map.reset_index()

# You can now plot this new dataframe exactly like we did before!
trreb_map.plot(edgecolor="black", color="lightblue")
plt.savefig("TRREB_Zones_Map.png", dpi=300, bbox_inches="tight")